services:
  fastapi:
    image: fastapi
    build: .
    ports:
      - 8000:8000
  

  streamlit:
    image: streamlit
    build: streamlit_app/.
    ports:
      - 8501:8501

    environment:
      API_URL: http://fastapi:8000