apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: steramlit
  name: streamlit
spec:
  ports:
  - name: "8501"
    nodePort: 30000
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: stramlit
  type: NodePort
status:
  loadBalancer: {}
