version: "3"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5555:5000"
    volumes:
      - ./mlartifacts:/mlartifacts
      - ./mlflow-db:/mlflow-db
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow-db/mlflow.db
      --artifacts-destination /mlartifacts
      --serve-artifacts
    container_name: mlflow-tracking-server